-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "bookingCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "bookingProfit" DOUBLE PRECISION NOT NULL DEFAULT 0;
