/**
 * Starter package templates for demo seeding (mirrors frontend packageQuickTemplates).
 */
module.exports = [
  {
    code: "TH-BKK-5N6D",
    title: "Bangkok & Pattaya Family Tour — 5 Nights / 6 Days",
    serviceType: "tour_international",
    summary: "Round-trip flights, hotels with breakfast, transfers, city tour, Coral Island.",
    destination: "Bangkok",
    country: "Thailand",
    durationDays: 6,
    durationNights: 5,
    basePrice: 45000,
    days: [
      { dayNumber: 1, title: "Arrival Bangkok", description: "Airport pickup and hotel check-in.", overnightLocation: "Bangkok" },
      { dayNumber: 2, title: "Bangkok City Tour", description: "Grand Palace, Wat Pho, Wat Arun.", overnightLocation: "Bangkok" },
      { dayNumber: 6, title: "Departure", description: "Checkout and airport transfer.", overnightLocation: "—" },
    ],
    inclusions: [
      { type: "included", label: "Return airfare", sortOrder: 0 },
      { type: "included", label: "Hotel with breakfast", sortOrder: 1 },
    ],
    pricing: [{ label: "Per person (twin share)", travelerMin: 2, travelerMax: null, price: 45000, currency: "BDT" }],
  },
  {
    code: "AE-DXB-4N5D",
    title: "Dubai Highlights — 4 Nights / 5 Days",
    serviceType: "tour_international",
    summary: "Flights, 4-star hotel, city tour, desert safari, Marina cruise.",
    destination: "Dubai",
    country: "United Arab Emirates",
    durationDays: 5,
    durationNights: 4,
    basePrice: 62000,
    visaRequired: true,
    days: [
      { dayNumber: 1, title: "Arrival Dubai", description: "Meet & greet, hotel check-in.", overnightLocation: "Dubai" },
      { dayNumber: 5, title: "Departure", description: "Checkout and airport transfer.", overnightLocation: "—" },
    ],
    inclusions: [
      { type: "included", label: "Return airfare", sortOrder: 0 },
      { type: "included", label: "Desert safari + dhow cruise", sortOrder: 1 },
    ],
    pricing: [{ label: "Per person (twin share)", travelerMin: 2, travelerMax: null, price: 62000, currency: "BDT" }],
  },
  {
    code: "UMR-ECO-10D",
    title: "Umrah Economy Package — 10 Days",
    serviceType: "hajj_umrah",
    summary: "Flights, Makkah + Madinah hotels, visa, transport, ziyarat.",
    destination: "Makkah",
    country: "Saudi Arabia",
    durationDays: 10,
    durationNights: 9,
    basePrice: 145000,
    visaRequired: true,
    days: [
      { dayNumber: 1, title: "Departure", description: "Flight from Dhaka.", overnightLocation: "Flight" },
      { dayNumber: 10, title: "Return", description: "Departure to Bangladesh.", overnightLocation: "—" },
    ],
    inclusions: [
      { type: "included", label: "Umrah visa", sortOrder: 0 },
      { type: "included", label: "Makkah & Madinah hotels", sortOrder: 1 },
    ],
    pricing: [{ label: "Per pilgrim", travelerMin: 1, travelerMax: null, price: 145000, currency: "BDT" }],
  },
  {
    code: "MY-KUL-4N5D",
    title: "Kuala Lumpur City Break — 4 Nights / 5 Days",
    serviceType: "tour_international",
    summary: "Flights, hotel, KL tour, Batu Caves, Genting day trip.",
    destination: "Kuala Lumpur",
    country: "Malaysia",
    durationDays: 5,
    durationNights: 4,
    basePrice: 38000,
    days: [
      { dayNumber: 1, title: "Arrival KL", description: "Airport transfer.", overnightLocation: "Kuala Lumpur" },
      { dayNumber: 5, title: "Departure", description: "Airport transfer.", overnightLocation: "—" },
    ],
    inclusions: [{ type: "included", label: "Return airfare + hotel B&B", sortOrder: 0 }],
    pricing: [{ label: "Per person (twin share)", travelerMin: 2, travelerMax: null, price: 38000, currency: "BDT" }],
  },
  {
    code: "SG-SIN-3N4D",
    title: "Singapore Family Holiday — 3 Nights / 4 Days",
    serviceType: "tour_international",
    summary: "Flights, hotel, Sentosa, Gardens by the Bay, Night Safari.",
    destination: "Singapore",
    country: "Singapore",
    durationDays: 4,
    durationNights: 3,
    basePrice: 52000,
    days: [
      { dayNumber: 1, title: "Arrival Singapore", description: "Transfer and check-in.", overnightLocation: "Singapore" },
      { dayNumber: 4, title: "Departure", description: "Airport transfer.", overnightLocation: "—" },
    ],
    inclusions: [{ type: "included", label: "Return airfare + hotel", sortOrder: 0 }],
    pricing: [{ label: "Per person (twin share)", travelerMin: 2, travelerMax: null, price: 52000, currency: "BDT" }],
  },
];
